@startuml
activate AbstractApplicationContext
AbstractApplicationContext->AbstractRefreshableApplicationContext:1.obtainFreshBeanFactory()
activate AbstractRefreshableApplicationContext
AbstractRefreshableApplicationContext->AbstractRefreshableApplicationContext:2.refreshBeanFactory()
activate AbstractRefreshableApplicationContext
activate DefaultListableBeanFactory
AbstractRefreshableApplicationContext->DefaultListableBeanFactory:3.createBeanFactory()
AbstractRefreshableApplicationContext<--DefaultListableBeanFactory
activate AbstractRefreshableApplicationContext
AbstractRefreshableApplicationContext->AbstractRefreshableApplicationContext:4.customizeBeanFactory()
activate AbstractXmlApplicationContext
AbstractRefreshableApplicationContext->AbstractXmlApplicationContext:5.loadBeanDefinitions()
activate XmlBeanDefinitionReader
AbstractXmlApplicationContext->XmlBeanDefinitionReader:6.new XmlBeanDefinitionReader()
XmlBeanDefinitionReader-->AbstractXmlApplicationContext
AbstractXmlApplicationContext-->AbstractRefreshableApplicationContext
AbstractApplicationContext<--AbstractRefreshableApplicationContext
@enduml